#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Regenerate the shipped partition tables from the code that defines the geometry.

The layouts are derived from Provisioning.hpp, not maintained by hand alongside
it. A table that disagrees with the code is worse than no table, because the
validator and the flasher would be checking a fiction -- and the fiction is what
ends up written to a board.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PART_DIR = ROOT / "firmware" / "partitions"
HEADER = ROOT / "firmware" / "include" / "bridge" / "Provisioning.hpp"

# Emitted by tools/dump-layout.cpp, kept here as a checked-in generator so the
# shipped CSVs can be rebuilt on a machine with only Python.
DUMP = """
#include <cstdio>
#include "bridge/Provisioning.hpp"

int main() {
  const std::uint8_t max = bridge::maxSlotsForFlash();
  std::printf("%u\\n", static_cast<unsigned>(max));
  std::printf("%s", bridge::renderSlots(max).c_str());
  std::printf("\\n@@SPLIT@@\\n");
  std::printf("%s", bridge::renderSlots(3).c_str());
  return 0;
}
"""


def build_dumper() -> Path | None:
    """Compile the layout dumper if a compiler is available. Otherwise fall back."""
    import shutil
    import tempfile

    cxx = None
    for cand in ("g++", "clang++", "c++"):
        cxx = shutil.which(cand)
        if cxx:
            break
    if not cxx:
        return None

    tmp = Path(tempfile.mkdtemp())
    src = tmp / "dump-layout.cpp"
    src.write_text(DUMP)
    exe = tmp / ("dump-layout.exe" if sys.platform == "win32" else "dump-layout")
    proc = subprocess.run(
        [
            cxx, "-std=c++17", f"-I{ROOT / 'firmware' / 'include'}",
            str(src), str(ROOT / "firmware" / "src" / "Provisioning.cpp"),
            str(ROOT / "firmware" / "src" / "SlotTable.cpp"), "-o", str(exe),
        ],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        return None
    return exe


HEADER_NOTE = """\
# Heltec WiFi LoRa 32 V4 -- {title}
#
# GENERATED by tools/gen_layouts.py from firmware/include/bridge/Provisioning.hpp.
# Edit the geometry there, not here; then run:  python tools/gen_layouts.py
#
# {body}
"""


def strip_leading_comments(csv: str) -> str:
    """Drop renderSlots()'s own header.

    The generated files carry a richer header written by this script; leaving
    renderSlots()'s comment above it produces two overlapping explanations of the
    same table, which is worse than either alone.
    """
    lines = [ln for ln in csv.splitlines() if not ln.lstrip().startswith("#")]
    return "\n".join(ln for ln in lines if ln.strip()) + "\n"


def main() -> int:
    exe = build_dumper()
    if exe is None:
        print("no C++ compiler available; cannot regenerate layouts", file=sys.stderr)
        return 2

    out = subprocess.run([str(exe)], capture_output=True, text=True)
    if out.returncode != 0:
        sys.stderr.write(out.stdout + out.stderr)
        return 2

    max_line, rest = out.stdout.split("\n", 1)
    full_csv, dual_csv = rest.split("@@SPLIT@@\n")
    max_slots = int(max_line.strip())
    full_csv = strip_leading_comments(full_csv)
    dual_csv = strip_leading_comments(dual_csv)

    PART_DIR.mkdir(parents=True, exist_ok=True)

    (PART_DIR / "quadboot.csv").write_text(
        HEADER_NOTE.format(
            title=f"{max_slots} slots, two of them in use.",
            body=(
                "Slot n lives at a fixed address whether there are two slots or five,\n"
                "# so this table can be rewritten in place to add a framework without ever\n"
                "# moving one that already holds firmware. That is the whole reason growth\n"
                "# is safe here, and it is what removes the need to think about this again.\n"
                "#\n"
                "#   ota_0 / fs_meshcore      MeshCore     live\n"
                "#   ota_1 / fs_meshtastic    Meshtastic   live\n"
                "#   ota_2 .. ota_4           reserved for frameworks not yet written\n"
                "#\n"
                "# Every app offset is 64KB aligned. The bootloader refuses a misaligned app\n"
                "# partition and reports nothing, so a board with one simply looks dead.\n"
                "#\n"
                "# Validate with: python tools/gate.py"
            ),
        )
        + "\n"
        + full_csv.rstrip()
        + "\n"
    )

    (PART_DIR / "dualboot.csv").write_text(
        HEADER_NOTE.format(
            title="three slots: two usable, one permanently free.",
            body=(
                "Just MeshCore and Meshtastic, with the rest of the flash left free.\n"
                "# A valid choice: a board is not obliged to reserve room it will never use.\n"
                "#\n"
                "# Meshtastic mounts LittleFS, MeshCore mounts SPIFFS. Give either side the\n"
                "# other's filesystem and it formats it on boot, destroying the other side's\n"
                "# settings with no error anywhere. Separate labels make that impossible.\n"
                "#\n"
                "# Validate with: python tools/gate.py"
            ),
        )
        + "\n"
        + dual_csv.rstrip()
        + "\n"
    )

    print(f"wrote {PART_DIR / 'quadboot.csv'} ({max_slots} slots)")
    print(f"wrote {PART_DIR / 'dualboot.csv'} (3 slots: 2 usable + 1 reserved free)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
